### ISSUE TITLE
multhread_q 我跑了下要500ns，可能原因是？

### ISSUE THREAD

**Issue by tedqian** [MengRao/SPSC_Queue#1]
机器配置：Gold 6144 3500MHZ，同一个node上面隔离出来2个CPU 绑核做的测试。
请问你的机器配置是啥能跑到50-100ns？或者需要做些其他的配置？

**Comment by MengRao** [comment]
打印的是cycles，要除以3.5换算成ns。

**Comment by robinzhang77** [comment]
SPSCQueue.h 70行
asm volatile("" : "=m"(data) : "m"(read_idx) :); // memory fence
是不是应该写成
asm volatile("" : : "m"(data), "m"(read_idx) :); // memory fence


asm不了解，我是看和push的写法不一样。。感觉是个原子操作的意思

**Comment by robinzhang77** [comment]
一对一的生产消费关系，感觉不需要加锁或是内存壁垒

**Comment by robinzhang77** [comment]
int a = 0;


void test1()
{
    for (int i = 0; i < 1000; i++)
    {
        asm volatile("" : : "m"(a) :);
        a++;
        asm volatile("" : : "m"(a) :);
        std::this_thread::sleep_for(std::chrono::milliseconds(1));
    }
}

void test2()
{
    for (int i = 0; i < 1000; i++)
    {
        asm volatile("" : : "m"(a) : );
        a--;
        asm volatile("" : : "m"(a) : );
        
        std::this_thread::sleep_for(std::chrono::milliseconds(1));
    }
}


两个线程跑。最后穿上a值不是0.。。是不是asm用错了？请教

**Comment by MengRao** [comment]
用C++11的atomic吧，别用asm了

**Comment by robinzhang77** [comment]
嗯。用std::atomic正常。。

但我现在有一个值是在共享内存中创建的，这个值两个进程在读写，我想保存它的原子性。
用std::atomic好象不行，照你的例子中用内存壁垒的写法，试了试，也不行，不知道是不是我的用法不对，求指教

**Comment by MengRao** [comment]
atomic可以用于两个进程读写

**Comment by robinzhang77** [comment]
例如：
int nVal = pSharedMemory->nVal;
这个nVal怎么变成std::atomic？

**Comment by MengRao** [comment]
`std::atomic<int>`，你最好先学习下c++11的atomic

**Comment by robinzhang77** [comment]
好的，谢谢，我去查查资料。
再问一下，那个asm volatile是不是只能在一行代码中保证原子性

asm volatile("" : : "m"(a) : );
a--;
asm volatile("" : : "m"(a) : );

这种三行，其实不能保证a的原子性，对吧

**Comment by MengRao** [comment]
https://zhuanlan.zhihu.com/p/41872203
看这篇文章

**Comment by robinzhang77** [comment]
感谢
